#!/bin/bash

yad --title "Theming Options" --escape-ok \
--form --center --width=220 --height=550 --borders=12 \
--text-align=center \
--window-icon=applications-utilities \
    --form \
    --field="System Options":LBL "" \
    --field="                  Auto Themes!$HOME/.config/lilidog-themes/icons/paw-theme-18.png!":FBTN "ld-themes" \
    --field="":LBL "" \
    --field="                              Conky!conky-logomark-violet":FBTN "conky-toggle" \
    --field="                         Font Size!font-x-generic":FBTN "fontsize-changer" \
    --field="                         Grub BG!org.xfce.settings.editor":FBTN "x-terminal-emulator -T 'Grub Background Changer' -e bash -c 'grub-bg-changer; echo $'\n\nPress any key to close.'; read -srn1'" \
    --field="                               Icons!preferences-other":FBTN "xfce4-appearance-settings" \
    --field="                           Jgmenu!jgmenu":FBTN "jg-icon-changer" \
    --field="                         LightDM!lightdm-gtk-greeter-settings":FBTN "gksudo lightdm-gtk-greeter-settings" \
    --field="             System Settings!preferences-system":FBTN "xfce4-settings-manager" \
    --field="             Terminal Colors!gnome-terminal":FBTN "ld-term-changer" \
    --field="                 Transparency!preferences-desktop":FBTN "transparency-system" \
    --field="                     Wallpapers!org.xfce.settings.display":FBTN "feh-set-wallpaper"
